version: '3'

services:
  mental-health-db:
    image: postgres:13.2-alpine
    container_name: mental-health-db
    environment:
      POSTGRES_DB: mental
      POSTGRES_USER: mental
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    networks:
      - mental-health_default

  mental-health-backend:
    container_name: mental-health-backend
    build: ./backend/
    command: uwsgi --ini uwsgi.ini --processes=4
#    command: python manage.py runserver 0.0.0.0:80
    env_file:
      - backend/.env
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:80
    depends_on:
      - mental-health-db
    networks:
      - mental-health_default

  mental-health-nginx:
    container_name: mental-health-nginx
    image: nginx:1.19.4-alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/proxy_backend.conf:/etc/nginx/proxy_backend.conf
      - ./nginx/conf/proxy_frontend.conf:/etc/nginx/proxy_frontend.conf
      - ./nginx/conf/proxy_params.conf:/etc/nginx/proxy_params.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./backend/static/:/data/static/
      - ./backend/media/:/data/media/
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mental-health-backend
    networks:
      - mental-health_default


networks:
  mental-health_default:
    external: true