# Generated by Django 3.1.3 on 2021-03-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSTestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'IN_PROGRESS'), (2, 'COMPLETED'), (3, 'NOT_COMPLETED')], default=1, verbose_name='Status')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_engine.pstest', verbose_name='Test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSTestStepHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(verbose_name='Ended at')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_engine.psteststep', verbose_name='Test Step')),
                ('test_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_history.pstesthistory', verbose_name='Test history')),
            ],
        ),
    ]
