# Generated by Django 3.1.3 on 2021-03-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_engine', '0002_auto_20210320_0024'),
        ('tests_history', '0003_auto_20210320_0135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='psteststephistory',
            unique_together={('test_history', 'step')},
        ),
    ]
