export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const UPDATE_CATEGORIES_LIST = "UPDATE_CATEGORIES_LIST";

export const GET_TEST_DETAIL = "GET_TEST_DETAIL";
export const EDIT_TEST = "EDIT_TEST";
export const EDIT_TEST_STEP = "EDIT_TEST_STEP";
export const RELOAD_TEST_STEP = "RELOAD_TEST_STEP";
export const ADD_TEST_STEP = "ADD_TEST_STEP";
export const DELETE_TEST_STEP = "DELETE_TEST_STEP";

export const IS_LOADING = "IS_LOADING";
export const END_LOADING = "END_LOADING";
