# Generated by Django 3.1.3 on 2021-03-20 18:15

import commons.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_history', '0004_auto_20210320_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pulse', commons.fields.PulseField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(300)], verbose_name='Pulse')),
                ('test_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_history.psteststephistory', verbose_name='Test Step History')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
