# Generated by Django 3.1.3 on 2021-03-14 21:44

import commons.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', commons.fields.PulseField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(300)], verbose_name='Pulse')),
                ('test_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_history.psteststephistory', verbose_name='Test Step History')),
            ],
        ),
    ]
