# Generated by Django 3.1.3 on 2021-03-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_history', '0004_auto_20210320_0139'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_test',
        ),
        migrations.AddField(
            model_name='user',
            name='last_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_history.psteststephistory', verbose_name='Last test step'),
        ),
    ]
