# Generated by Django 3.1.3 on 2021-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210321_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'MElA'), (2, 'FEMALE')], null=True, verbose_name='Sex'),
        ),
    ]
