# Generated by Django 3.1.3 on 2021-03-21 16:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210321_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_directory_path, verbose_name='Avatar'),
        ),
    ]
